### ISSUE TITLE
main.dart is not available 

### ISSUE THREAD

**Issue by RohitSadioura** [1akhanBaheti/FlutterKanbanBoard#1]
main.dart is not available

**Comment by RohitSadioura** [comment]
there should be add new list feature in this kanban Board view . like in trello . when all horizontal list loads then at the end there is a new list add feature .. that will be very useful pls implement that

**Comment by 1akhanBaheti** [comment]
> main.dart is not available

Hi RohitSadioura,
There is example.dart file in example folder you consider it as main.dart.

**Comment by 1akhanBaheti** [comment]
> there should be add new list feature in this kanban Board view . like in trello . when all horizontal list loads then at the end there is a new list add feature .. that will be very useful pls implement that

Yeah sure, I will add it in next version.
