### ISSUE TITLE
The Board is not scrollable on desktops (Linux and Windows)

### ISSUE THREAD

**Issue by quasar-pankaj** [1akhanBaheti/FlutterKanbanBoard#3]
Hello Lakhan,
I am using this library in a project of mine which is targeting all the platforms supported by Flutter. Of all the libraries I have tried so far I have found this to be the best functionality-wise. While testing it on Linux and Windows I have run into a problem, I can't scroll horizontally on desktops(Linux and windows). I have tried the following workaround but that too doesn't seem to work - [This Workaround](https://github.com/flutter/website/blob/9fd9aceffbc9bb1a0aa1a751c85409e044a8d059/src/docs/release/breaking-changes/default-scroll-behavior-drag.md). Could you please check? Here are a few suggestions:-
1. You can make it draggable using the mouse the functionality will be similar to what it is on the mobile platform.
2. Or you can add a setting in the board which will allow the user to always show the scrollbars. This seems like the best solution.
3. I tried to add my own scrollbar to the board but flutter requires that the controller of the scrollbar and the board to be same. This could solve the issue if there was a way to pass scroll controller to the board or to get its controller somehow.
Thanks,
Pankaj

**Comment by 1akhanBaheti** [comment]
Hi @quasar-pankaj, got the issue, I am going to push new release in that this will be fixed

**Comment by 1akhanBaheti** [comment]
HI @quasar-pankaj, you can check new release, its pushed.

**Comment by quasar-pankaj** [comment]
I will check it out. Thanks.

**Comment by quasar-pankaj** [comment]
It's scrolling now. Thanks.
